openapi: 3.0.0
info:
  title: Swagger specification
  version: 1.0.0
components:
  schemas:
    Transaction:
      type: object
      description: Describes a Wallet transaction.
      additionalProperties: false
      properties:
        RealMoneyBalance:
          type: number
          description: Wallet real money balance of the player after transaction.
          format: decimal
        ComplexProperty:
          description: Describes a complex property
          oneOf:
            - $ref: '#/components/schemas/ComplexProperty'
    ComplexProperty:
      type: object
      description: Describes a complex object
      additionalProperties: false
      properties:
        Foo:
          type: string
          description: something important
